export const index = "Index Page"
export const characterSheet = "Character sheet and homepage"
export const loginPage = "Login page"
export const registerScreen = "register"
export const gameRoom = "Game room"
