export const index = "Index Page"
export const characterSheet = "Character sheet and homepage"
export const loginPage = "Login page"
export const createAccount = "Create account"
export const gameRoom = "Game room"
