export const DASHBOARD = "Dashboard"
export const HOMEPAGE = "Home dashboard"
export const LOGIN_PAGE = "Login page"
export const CREATE_ACCOUNT = "Create account"
export const GAME_ROOM = "Game room"
export const FORGOT_PASSWORD = "Forgot password screen"
